### ISSUE TITLE
Tool for generating the github profile summary

### ISSUE THREAD

**Issue by mainrs** [abhisheknaiidu/abhisheknaiidu#1]
What tool did you use to generate the very last image on this repo?

**Comment by abhisheknaiidu** [comment]
It's [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) by @anuraghazra

**Comment by anuraghazra** [comment]
This is the reason i'm planning to do this, https://github.com/anuraghazra/github-readme-stats/issues/90

:D Your opinions and thoughts on this is appreciated.
