### ISSUE TITLE
i took the GIF 

### ISSUE THREAD

**Issue by yezz123** [abhisheknaiidu/abhisheknaiidu#2]
@abhisheknaiidu i Took the Gif cause is good 👍🙏.
 this is my profile :
 https://github.com/yezz123/yezz123

**Comment by abhisheknaiidu** [comment]
@yezz123 Thanks Bro 😍, but it's not visible, lol

**Comment by shadialtarsha** [comment]
Can I use your gif @yezz123 ? 😅 
I really like your Github profile

**Comment by yezz123** [comment]
@shadialtarsha  Yes Use it no problem man!
